apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: changeme
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/xieweicarl2018/ng-golang-http-80-xieweicarl2018:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - docker: {}
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/xieweicarl2018/ng-golang-http-80-xieweicarl2018:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: ng-golang-http-80-xieweicarl2018
        chartPath: charts/ng-golang-http-80-xieweicarl2018
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/xieweicarl2018/ng-golang-http-80-xieweicarl2018'
          image.tag: '{{.DIGEST_HEX}}'
